
import { AIAdventureGame } from "@/components/ai-adventure-game";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";
import Link from "next/link";

export default function AIAdventurePage() {
  return (
    <div className="container mx-auto px-4 py-8">
       <div className="mb-6">
        <Button variant="ghost" asChild>
          <Link href="/" className="flex items-center text-sm text-muted-foreground hover:text-foreground">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Home
          </Link>
        </Button>
      </div>
      <div className="text-center mb-8">
        <h1 className="text-4xl font-black tracking-tight lg:text-5xl shimmer-text">
          AI Adventure
        </h1>
        <p className="mt-2 text-lg text-muted-foreground max-w-2xl mx-auto">
            A unique story and image are generated by AI just for you. Write a creative ending to win!
        </p>
      </div>

      <AIAdventureGame productName="The Adventurer's Golden Key" />

    </div>
  );
}
