
import { AIAdventureGame } from "@/components/ai-adventure-game";

export default function AIAdventurePage() {
  return (
    <div className="container mx-auto px-4 py-8">
      <div className="text-center mb-8">
        <h1 className="text-4xl font-black tracking-tight lg:text-5xl shimmer-text">
          AI Adventure
        </h1>
        <p className="mt-2 text-lg text-muted-foreground max-w-2xl mx-auto">
            A unique story and image are generated by AI just for you. Write a creative ending to win!
        </p>
      </div>

      <AIAdventureGame productName="The Adventurer's Golden Key" />

    </div>
  );
}
