
export interface Product {
  id: string;
  name: string;
  marketPrice: number;
  imageUrl: string;
  dataAiHint: string;
}

export const mockProducts: Product[] = [
  {
    id: "prod_001",
    name: "Vintage 'Cosmic Rift' Arcade Machine",
    marketPrice: 2500.0,
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "arcade machine",
  },
  {
    id: "prod_002",
    name: "Limited Edition Holographic Sneakers",
    marketPrice: 750.0,
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "holographic sneakers",
  },
  {
    id: "prod_003",
    name: "Self-Watering Smart Planter",
    marketPrice: 120.5,
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "smart planter",
  },
  {
    id: "prod_004",
    name: "Gourmet Molecular Gastronomy Kit",
    marketPrice: 199.99,
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "gastronomy kit",
  },
  {
    id: "prod_005",
    name: "GRAV-LEVITRON Hoverboard",
    marketPrice: 1850.0,
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "hoverboard",
  },
  {
    id: "prod_006",
    name: "Retro-Futuristic Nixie Tube Clock",
    marketPrice: 350.0,
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "nixie clock",
  },
  {
    id: "prod_007",
    name: "AI-Powered Personal Chef Bot",
    marketPrice: 3200.0,
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "robot chef",
  },
  {
    id: "prod_008",
    name: "Signed First Edition 'Neuromancer'",
    marketPrice: 4800.0,
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "rare book",
  },
  {
    id: 'prod_009',
    name: 'DIY Gene Editing Kit',
    marketPrice: 1250.75,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'science kit',
  },
  {
    id: 'prod_010',
    name: 'Personal Weather Control Drone',
    marketPrice: 7800.0,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'weather drone',
  },
  {
    id: 'prod_011',
    name: 'Anti-Gravity Yoga Mat',
    marketPrice: 220.0,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'yoga mat',
  },
  {
    id: 'prod_012',
    name: 'Zero-G Space Pen',
    marketPrice: 85.0,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'space pen',
  },
  {
    id: 'prod_013',
    name: "'Pocket Galaxy' Mini Hologram Projector",
    marketPrice: 150.0,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'hologram projector',
  },
  {
    id: 'prod_014',
    name: "'Aura-Ring' Mood & Biometric Tracker",
    marketPrice: 280.0,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'smart ring',
  },
  {
    id: 'prod_015',
    name: "'Zenith' Levitating Air Bonsai Pot",
    marketPrice: 180.5,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'levitating planter',
  },
  {
    id: 'prod_016',
    name: 'Cryo-Stasis Sleep Pod (Rental)',
    marketPrice: 5500.0,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'sleep pod',
  },
  {
    id: 'prod_017',
    name: 'Sonic-Cleanse Multi-Tool',
    marketPrice: 95.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'ultrasonic cleaner',
  },
  {
    id: 'prod_018',
    name: "Autonomous 'Courier-Bot' Companion",
    marketPrice: 2100.0,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'delivery robot',
  },
  {
    id: 'prod_019',
    name: 'Graphene-Weave All-Weather Jacket',
    marketPrice: 620.0,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'smart jacket',
  },
  {
    id: 'prod_020',
    name: 'Portable Fusion Power Bank',
    marketPrice: 15000.0,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'power bank',
  },
  {
    id: "prod_021",
    name: "Pocket-Sized Drone with 4K Camera",
    marketPrice: 129.99,
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "mini drone",
  },
  {
    id: "prod_022",
    name: "Smart Coffee Mug with Temp Control",
    marketPrice: 89.50,
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "smart mug",
  },
  {
    id: "prod_023",
    name: "Portable Outdoor Pizza Oven",
    marketPrice: 299.0,
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "pizza oven",
  },
  {
    id: "prod_024",
    name: "Sunrise Simulator Alarm Clock",
    marketPrice: 45.0,
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "alarm clock",
  },
  {
    id: "prod_025",
    name: "Noise-Cancelling Acoustic Wallpaper",
    marketPrice: 450.0,
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "acoustic wallpaper",
  },
  {
    id: "prod_026",
    name: "Augmented Reality Stargazing Telescope",
    marketPrice: 850.0,
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "ar telescope",
  },
  {
    id: "prod_027",
    name: "Personalized Vitamin & Supplement 3D Printer",
    marketPrice: 1200.0,
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "vitamin printer",
  },
  {
    id: "prod_028",
    name: "Hydro-Powered Floating Speaker",
    marketPrice: 75.0,
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "floating speaker",
  },
  {
    id: "prod_029",
    name: "Kinetic Sand 'Zen Garden' Desk Toy",
    marketPrice: 35.0,
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "desk toy",
  },
  {
    id: "prod_030",
    name: "Self-Healing Protective Phone Case",
    marketPrice: 65.0,
    imageUrl: "https://placehold.co/600x400.png",
    dataAiHint: "phone case",
  },
];

    