
import { getFirestore, collection, getDocs } from 'firebase/firestore';
import { app } from './firebase'; // Import the initialized app

export interface Product {
  id: string;
  name: string;
  subtitle: string;
  description: string;
  marketPrice: number;
  imageUrl: string;
  dataAiHint: string;
  expertSystem: string;
  game?: 'reel-pause' | 'multi-shot' | 'riddle-calc' | 'draw-passcode' | 'chess-mate' | 'time-challenge' | 'pink-cups' | 'snake-and-stairs' | 'ai-adventure' | 'maze-draw' | 'story-match' | 'mirror-game';
  category?: 'luckshot' | 'brainshot' | 'luckgirls' | 'chess' | 'electronics' | 'fashion' | 'home' | 'collectibles' | 'voucher';
  status?: 'Hot' | 'New' | 'Testing';
}

const db = getFirestore(app); // Use the imported, initialized app

export async function getProducts(): Promise<Product[]> {
  // Mock data for products. In a real app, this would fetch from Firestore.
  // const productsCol = collection(db, 'products');
  // const productsSnapshot = await getDocs(productsCol);
  // const productsList = productsSnapshot.docs.map(doc => ({ id: doc.id, ...doc.data() } as Product));
  // return productsList;
  return Promise.resolve(mockProducts);
}

// Keep one or two products for fallback or initial state if needed
export const mockProducts: Product[] = [
    // --- VOUCHERS ---
    {
        id: 'voucher_10',
        name: '$10 Store Voucher',
        subtitle: 'Your Choice, Your Store',
        description: 'A digital voucher for the online store of your choice.',
        marketPrice: 10.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'gift card',
        expertSystem: 'Win this in the Shop Hunter game and choose your reward.',
        category: 'voucher',
    },
    {
        id: 'voucher_25',
        name: '$25 Store Voucher',
        subtitle: 'Your Choice, Your Store',
        description: 'A digital voucher for the online store of your choice.',
        marketPrice: 25.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'gift card',
        expertSystem: 'Win this in the Shop Hunter game and choose your reward.',
        category: 'voucher',
    },
    {
        id: 'voucher_50',
        name: '$50 Store Voucher',
        subtitle: 'Your Choice, Your Store',
        description: 'A digital voucher for the online store of your choice.',
        marketPrice: 50.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'gift card',
        expertSystem: 'Win this in the Shop Hunter game and choose your reward.',
        category: 'voucher',
    },
    {
        id: 'voucher_100',
        name: '$100 Store Voucher',
        subtitle: 'Your Choice, Your Store',
        description: 'A digital voucher for the online store of your choice.',
        marketPrice: 100.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'gift card',
        expertSystem: 'Win this in the Shop Hunter game and choose your reward.',
        category: 'voucher',
    },
    {
        id: 'voucher_200',
        name: '$200 Store Voucher',
        subtitle: 'Your Choice, Your Store',
        description: 'A digital voucher for the online store of your choice.',
        marketPrice: 200.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'gift card',
        expertSystem: 'Win this in the Shop Hunter game and choose your reward.',
        category: 'voucher',
    },
    {
        id: 'voucher_500',
        name: '$500 Store Voucher',
        subtitle: 'Your Choice, Your Store',
        description: 'A digital voucher for the online store of your choice.',
        marketPrice: 500.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'gift card',
        expertSystem: 'Win this in the Shop Hunter game and choose your reward.',
        category: 'voucher',
    },
    
    // --- BRAINSHOTS (SKILL-BASED) ---
    {
        id: 'prod_phone_01',
        name: 'SuperPhone XVI',
        subtitle: 'The Ultimate Smartphone',
        description: 'The latest and greatest, featuring the A20 Fusion chip and a revolutionary camera system.',
        marketPrice: 1299.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'smartphone mockup',
        expertSystem: 'The price is hidden behind a fast-spinning reel of numbers. Click "Pause" to freeze the reel, then select three digits to form your price.',
        game: 'reel-pause',
        category: 'brainshot',
        status: 'Hot',
    },
    {
        id: 'prod_crypto_01',
        name: '$500 Bitcoin Prize',
        subtitle: 'Solve the Riddle',
        description: "A prize of $500 in Bitcoin, credited to your account. Solve the riddle to claim it.",
        marketPrice: 500.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'bitcoin treasure',
        expertSystem: 'This item\'s price is locked behind a riddle. Click "Start Challenge", use the on-card calculator to punch in the correct answer. If you solve it, you can buy the item for a fixed, low price.',
        game: 'riddle-calc',
        category: 'brainshot',
    },
    {
        id: 'prod_math_01',
        name: 'MathMoney Prize',
        subtitle: 'Win 42 Shots!',
        description: "Solve the math problem to win a prize of 42 Shots, credited to your account.",
        marketPrice: 42.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'math formula',
        expertSystem: 'This item\'s price is locked behind a math problem. Click "Start Challenge" to begin the timer and use the on-card calculator to punch in the correct answer.',
        game: 'riddle-calc',
        category: 'brainshot',
    },
    {
        id: 'prod_headset_01',
        name: 'NeuroLink VR',
        subtitle: 'Immersive Virtual Reality',
        description: 'Step into new worlds with this high-end VR headset, featuring stunning visuals and intuitive controls.',
        marketPrice: 499.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'futuristic headset',
        expertSystem: 'A secret pattern is the key. Click "Start Challenge" and a pattern will flash on screen. Memorize it, then draw it on the 3x3 grid to unlock the prize.',
        game: 'draw-passcode',
        category: 'brainshot',
        status: 'New',
    },
    {
        id: 'prod_maze_01',
        name: '$5 Voucher Prize',
        subtitle: 'Solve the Pathfinder Maze',
        description: 'Navigate the maze from start to finish to win a $5 voucher, credited as 5 Shots to your account.',
        marketPrice: 5.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'glowing maze',
        expertSystem: 'A timed Pathfinder puzzle. Click "Start Game" and draw the correct path from start (S) to end (E) before the timer runs out to win the prize!',
        game: 'maze-draw',
        category: 'brainshot',
    },
    {
        id: 'prod_mirror_01',
        name: 'The Mirror Shard',
        subtitle: 'A Fragment of Perception',
        description: 'A beautiful, shimmering shard that seems to reflect more than just light. A prize for those with keen observation.',
        marketPrice: 25.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'glowing crystal',
        expertSystem: 'Shooter creates a pattern on a grid. It is revealed for a moment. You must perfectly mirror his pattern on your own grid to win this prize for free.',
        game: 'mirror-game',
        category: 'brainshot',
        status: 'Testing',
    },
    {
        id: 'prod_chess_01',
        name: 'Checkmate Challenge Prize',
        subtitle: 'Solve for 500 Shots',
        description: 'A special chess puzzle. Find the checkmate in one move to win a massive prize of 500 Shots.',
        marketPrice: 500,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'glowing chesspiece',
        expertSystem: 'A "Checkmate in One" puzzle. You are playing as White. Analyze the board and make the single move that puts the Black king in checkmate to win.',
        game: 'chess-mate',
        category: 'brainshot',
    },
    {
        id: 'prod_adventure_01',
        name: "The Adventurer's Key",
        subtitle: 'A Special Prize',
        description: 'A golden key that unlocks a special prize for those who can prove their creativity in the AI Adventure.',
        marketPrice: 50,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'ornate key',
        expertSystem: 'The AI has started a story and created an image. It\'s up to you to write the perfect ending.',
        game: 'ai-adventure',
        category: 'brainshot',
    },

    // --- LUCKGIRLS (SOCIAL GAMES) ---
    {
        id: 'prod_luckgirl_01',
        name: 'Time Challenge',
        subtitle: 'Beat the clock!',
        description: 'A fast-paced puzzle game. Solve as many mini-puzzles as you can before the time runs out.',
        marketPrice: 10,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'anime girl pink',
        expertSystem: 'A fast-paced puzzle game. Solve as many mini-puzzles as you can before the time runs out.',
        game: 'time-challenge',
        category: 'luckgirls',
    },
    {
        id: 'prod_luckgirl_02',
        name: 'Pink Cups',
        subtitle: 'Find the lucky cup!',
        description: 'A classic shell game with a fun twist. Keep your eye on the pink cup to win the prize.',
        marketPrice: 10,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'anime girl purple',
        expertSystem: 'A classic shell game with a fun twist. Keep your eye on the pink cup to win the prize.',
        game: 'pink-cups',
        category: 'luckgirls',
    },
    {
        id: 'prod_luckgirl_03',
        name: 'Snake and Stairs',
        subtitle: 'Social board game',
        description: 'A social board game where you can chat with your opponent and the audience. Roll the dice and climb to victory!',
        marketPrice: 10,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'anime girl blue',
        expertSystem: 'A social board game where you can chat with your opponent and the audience. Roll the dice and climb to victory!',
        game: 'snake-and-stairs',
        category: 'luckgirls',
    },
    {
        id: 'prod_luckgirl_04',
        name: 'Story Match',
        subtitle: 'Connect the narrative',
        description: 'A social deduction game where players match story snippets to win. Who is telling the truth?',
        marketPrice: 10,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'anime girl blonde',
        expertSystem: 'A social deduction game where players match story snippets to win. Who is telling the truth?',
        game: 'story-match',
        category: 'luckgirls',
    },

    // --- LUCKSHOTS (DYNAMIC PRICING) ---
    // --- ELECTRONICS ---
    {
        id: 'prod_console_01',
        name: 'Orion Game Console',
        subtitle: 'Next-Generation Gaming',
        description: 'Experience lightning-fast loading and breathtaking graphics with the latest gaming console.',
        marketPrice: 599.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'game console',
        expertSystem: 'Instead of one, you get three shots at a great price! Click the "x3 Shot" button to capture three different prices simultaneously. Review the three options and pick the best one.',
        game: 'multi-shot',
        category: 'luckshot',
        status: 'Hot',
    },
    {
        id: 'prod_laptop_01',
        name: 'Blade Gaming Laptop',
        subtitle: 'Power on the Go',
        description: 'A high-performance gaming laptop with a top-of-the-line GPU and a high-refresh-rate-screen.',
        marketPrice: 1999.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'gaming laptop',
        expertSystem: 'The price of this item is constantly changing. Watch the chart and click the "Shot" button when you see a price you like to capture it.',
        category: 'luckshot',
    },
    {
        id: 'prod_camera_01',
        name: 'Lumix DSLR Camera',
        subtitle: 'Professional Photography',
        description: 'Capture stunning, high-resolution photos and 4K video with this professional-grade DSLR camera.',
        marketPrice: 899.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'professional camera',
        expertSystem: 'The price of this item is constantly changing. Watch the chart and click the "Shot" button when you see a price you like to capture it.',
        category: 'luckshot',
    },
    {
        id: 'prod_drone_01',
        name: 'Hornet 4K Drone',
        subtitle: 'Aerial Cinematography',
        description: 'Explore the world from a new perspective and capture breathtaking aerial shots with this 4K drone.',
        marketPrice: 799.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'flying drone',
        expertSystem: 'The price of this item is constantly changing. Watch the chart and click the "Shot" button when you see a price you like to capture it.',
        category: 'luckshot',
        status: 'New'
    },
    {
        id: 'prod_smartwatch_01',
        name: 'Momentum Smartwatch',
        subtitle: 'Your Life on Your Wrist',
        description: 'Track your fitness, stay connected, and monitor your health with the latest smartwatch technology.',
        marketPrice: 450.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'smart watch',
        expertSystem: 'The price of this item is constantly changing. Watch the chart and click the "Shot" button when you see a price you like to capture it.',
        category: 'luckshot',
    },
     {
        id: 'prod_tablet_01',
        name: 'Canvas Pro Tablet',
        subtitle: 'Creativity Unleashed',
        description: 'A powerful and versatile tablet perfect for artists, designers, and professionals on the go.',
        marketPrice: 999.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'drawing tablet',
        expertSystem: 'The price of this item is constantly changing. Watch the chart and click the "Shot" button when you see a price you like to capture it.',
        category: 'luckshot',
    },
    {
        id: 'prod_headphones_01',
        name: 'Aura Headphones',
        subtitle: 'Immersive Audio Experience',
        description: 'Block out distractions and enjoy pure, high-fidelity sound with these premium noise-cancelling headphones.',
        marketPrice: 349.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'studio headphones',
        expertSystem: 'The price of this item is constantly changing. Watch the chart and click the "Shot" button when you see a price you like to capture it.',
        category: 'luckshot',
        status: 'Hot',
    },

    // --- FASHION ---
    {
        id: 'prod_sneakers_01',
        name: 'Grail Sneakers',
        subtitle: 'Iconic Streetwear',
        description: 'A highly sought-after pair of limited edition sneakers from a top designer collaboration.',
        marketPrice: 650.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'hype sneakers',
        expertSystem: 'The price of this item is constantly changing. Watch the chart and click the "Shot" button when you see a price you like to capture it.',
        category: 'luckshot',
    },
    {
        id: 'prod_handbag_01',
        name: 'Artisan Handbag',
        subtitle: 'Timeless Elegance',
        description: 'A classic, handcrafted leather handbag from a world-renowned luxury brand. A statement piece for any collection.',
        marketPrice: 2500.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'luxury handbag',
        expertSystem: 'The price of this item is constantly changing. Watch the chart and click the "Shot" button when you see a price you like to capture it.',
        category: 'luckshot',
    },
    {
        id: 'prod_jacket_01',
        name: 'Nomad Denim Jacket',
        subtitle: 'Retro Cool',
        description: 'A perfectly worn-in vintage denim jacket with unique patches and a story to tell.',
        marketPrice: 250.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'patched jacket',
        expertSystem: 'The price of this item is constantly changing. Watch the chart and click the "Shot" button when you see a price you like to capture it.',
        category: 'luckshot',
    },
    {
        id: 'prod_sunglasses_01',
        name: 'Icon Sunglasses',
        subtitle: 'Effortless Style',
        description: 'Protect your eyes and elevate your look with these stylish sunglasses from a luxury fashion house.',
        marketPrice: 420.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'fashion sunglasses',
        expertSystem: 'The price of this item is constantly changing. Watch the chart and click the "Shot" button when you see a price you like to capture it.',
        category: 'luckshot',
    },

    // --- HOME & LIFESTYLE ---
    {
        id: 'prod_coffeemachine_01',
        name: 'Barista Espresso Machine',
        subtitle: 'Cafe-Quality Coffee',
        description: 'Craft perfect lattes, cappuccinos, and espressos at home with this professional-grade machine.',
        marketPrice: 850.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'coffee machine',
        expertSystem: 'The price of this item is constantly changing. Watch the chart and click the "Shot" button when you see a price you like to capture it.',
        category: 'luckshot',
    },
    {
        id: 'prod_chair_01',
        name: 'Atlas Office Chair',
        subtitle: 'Ultimate Comfort & Support',
        description: 'Upgrade your workspace with this top-rated ergonomic chair, designed for all-day comfort.',
        marketPrice: 550.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'ergonomic chair',
        expertSystem: 'The price of this item is constantly changing. Watch the chart and click the "Shot" button when you see a price you like to capture it.',
        category: 'luckshot',
    },
    {
        id: 'prod_art_01',
        name: 'Genesis Canvas Art',
        subtitle: 'Signed by the Artist',
        description: 'A beautiful, one-of-a-kind abstract painting on canvas, signed by an emerging contemporary artist.',
        marketPrice: 1200.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'abstract art',
        expertSystem: 'The price of this item is constantly changing. Watch the chart and click the "Shot" button when you see a price you like to capture it.',
        category: 'luckshot',
    },

    // --- COLLECTIBLES ---
    {
        id: 'prod_card_01',
        name: 'Gemstone Dragon Card',
        subtitle: 'Holographic First Edition',
        description: 'A mint-condition, holographic first edition of a legendary trading card. A true collector\'s dream.',
        marketPrice: 3500.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'holographic card',
        expertSystem: 'The price of this item is constantly changing. Watch the chart and click the "Shot" button when you see a price you like to capture it.',
        category: 'luckshot',
        status: 'Hot',
    },
    {
        id: 'prod_figure_01',
        name: 'Galaxy Trooper Figure',
        subtitle: 'In Original Packaging',
        description: 'A rare, vintage action figure from the 1980s, still sealed in its original packaging.',
        marketPrice: 480.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'retro actionfigure',
        expertSystem: 'The price of this item is constantly changing. Watch the chart and click the "Shot" button when you see a price you like to capture it.',
        category: 'luckshot',
    },
    {
        id: 'prod_coin_01',
        name: 'Ancient Silver Drachma',
        subtitle: 'Certified Historical Artifact',
        description: 'A genuine silver coin from an ancient empire, professionally graded and certified.',
        marketPrice: 950.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'silver coin',
        expertSystem: 'The price of this item is constantly changing. Watch the chart and click the "Shot" button when you see a price you like to capture it.',
        category: 'luckshot',
    },
     {
        id: 'prod_tv_01',
        name: 'CinemaView 8K TV',
        subtitle: 'The Ultimate Home Theater',
        description: 'Transform your living room into a cinema with this massive 77-inch 8K OLED TV.',
        marketPrice: 3499.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'oled tv',
        expertSystem: 'The price of this item is constantly changing. Watch the chart and click the "Shot" button when you see a price you like to capture it.',
        category: 'luckshot',
    },
    {
        id: 'prod_blender_01',
        name: 'Vortex Blender',
        subtitle: 'Smoothies, Soups, and More',
        description: 'A powerful blender that can handle anything from silky smoothies to hot soups.',
        marketPrice: 450.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'powerful blender',
        expertSystem: 'The price of this item is constantly changing. Watch the chart and click the "Shot" button when you see a price you like to capture it.',
        category: 'luckshot',
    },
    {
        id: 'prod_bike_01',
        name: 'E-Bike Dominator',
        subtitle: 'Conquer Any Trail',
        description: 'A rugged electric mountain bike with a powerful motor and long-lasting battery to take on any adventure.',
        marketPrice: 2800.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'electric bike',
        expertSystem: 'The price of this item is constantly changing. Watch the chart and click the "Shot" button when you see a price you like to capture it.',
        category: 'luckshot',
    },
    {
        id: 'prod_keyboard_01',
        name: 'RGB Mechanical Keyboard',
        subtitle: 'Ultimate Typing Experience',
        description: 'A premium mechanical keyboard with customizable RGB lighting and satisfying tactile switches.',
        marketPrice: 180.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'rgb keyboard',
        expertSystem: 'The price of this item is constantly changing. Watch the chart and click the "Shot" button when you see a price you like to capture it.',
        category: 'luckshot',
    },
     {
        id: 'prod_subscription_01',
        name: 'Lifetime Music Subscription',
        subtitle: 'Unlimited Streaming Forever',
        description: 'A one-time purchase for a lifetime subscription to a leading music streaming service.',
        marketPrice: 600.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'music subscription',
        expertSystem: 'Instead of one, you get three shots at a great price! Click the "x3 Shot" button to capture three different prices simultaneously. Review the three options and pick the best one.',
        game: 'multi-shot',
        category: 'luckshot',
    },
    {
        id: 'prod_watch_01',
        name: 'Prestige Swiss Watch',
        subtitle: 'Automatic Movement',
        description: 'An exquisite Swiss-made timepiece featuring a sophisticated automatic movement and sapphire crystal.',
        marketPrice: 4500.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'swiss watch',
        expertSystem: 'The price of this item is constantly changing. Watch the chart and click the "Shot" button when you see a price you like to capture it.',
        category: 'luckshot',
        status: 'Hot'
    },
    {
        id: 'prod_vr_gloves_01',
        name: 'Haptic VR Gloves',
        subtitle: 'Feel the Virtual World',
        description: 'A pair of advanced haptic gloves that let you feel textures and interactions in virtual reality.',
        marketPrice: 899.0,
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'haptic gloves',
        expertSystem: 'A secret pattern is the key. Click "Start Challenge" and a pattern will flash on screen. Memorize it, then draw it on the 3x3 grid to unlock the prize.',
        game: 'draw-passcode',
        category: 'brainshot',
    },
     {
        id: 'prod_chess_challenge_01',
        name: 'Head-to-Head Chess',
        subtitle: '1v1 Puzzle Speedrun',
        description: 'Challenge another player to a head-to-head chess puzzle speedrun. First to solve wins the prize.',
        marketPrice: 100, // Represents the prize pool
        imageUrl: 'https://placehold.co/600x400.png',
        dataAiHint: 'glowing chess',
        expertSystem: 'This is a "Checkmate in One" puzzle. You are playing as White. Analyze the board and make the single move that puts the Black king in checkmate. If you find the correct move, you instantly win the prize.',
        game: 'chess-mate',
        category: 'chess',
    },
];
