name: Node.js CI

on:
 push:
 branches: [ "main" ]
 pull_request:
 branches: [ "main" ]

jobs:
 build:
 runs-on: ubuntu-latest

 steps:
 - uses: actions/checkout@v4
 - name: Use Node.js
 uses: actions/setup-node@v4
 with:
 node-version: '20.x'
 cache: 'npm'
 - name: Clean node_modules
 run: rm -rf node_modules
 - name: Install dependencies
 run: npm ci
 - name: Build
 run: npm run build --if-present
 - name: List files
 run: ls -al
 - name: Run tests
 run: npm test
